### ISSUE TITLE
Use React 16 portals

### ISSUE THREAD

**Issue by agentcooper** [agentcooper/react-pdf-highlighter#10]
Code should use [portals](https://reactjs.org/docs/portals.html) instead of calling `ReactDOM.render` inside `renderHighlights`.

**Comment by idibidiart** [comment]
hey nice work

what's the advantage of using portals here?

**Comment by agentcooper** [comment]
Thank you.

At the moment I use ReactDOM.render to render highlights inside the existing PDF.js structure. The disadvantage is the loss of the context. If you use Redux in your app, the Highlight component won't have access to the store, so that you'll need to wrap Highlight in Provider manually.

**Comment by idibidiart** [comment]
Awesome. 

For others who are curious:

"Features like context work exactly the same regardless of whether the child is a portal, as the portal still exists in the React tree regardless of position in the DOM tree."  source: React docs on Portals

Makes sense in case of Redux but I agree it's a nice to have. 

Great great work. Looking forward to hacking on it!
