### ISSUE TITLE
Poll: TypeScript

### ISSUE THREAD

**Issue by agentcooper** [agentcooper/react-pdf-highlighter#107]
Please let me know if you're interested in typings for this library. I did it many years ago and chose Flow at the time, but it is now clear that TypeScript is the winner here.

If you're interested, please do a 👍 on this message.

**Comment by siyachili** [comment]
@agentcooper The typescipt is not available yet?

**Comment by Vagizova** [comment]
I am interested!! I'm stuck on this and can't move on, I can't even run this on empty 'create-react-app' (npx create-react-app my-app --template typescript) ... is there any chance here to run this library with this configuration? do you have any advice for me?
