### ISSUE TITLE
pdfjs-dist bundle size

### ISSUE THREAD

**Issue by jinman** [agentcooper/react-pdf-highlighter#112]
We use CRA and have pdfjs-dist as dependencies and worker-loader as devDependencies in packages.json and are using (import PDFWorker from "worker-loader!pdfjs-dist/build/pdf.worker"; ) in our code as shown in the example. 

Since we have two places we show react-pdf-highlighter (one during adding highlights and other to show the highlights) in our app, we are referencing the PDFWorker twice. Not sure if that is the best practice? How do we reuse?

Due to this, our bundle-size (source-map-explorer) shows as PDFJS-DIST 840KB and each PDF.WORKER as 699 KB. Total is 840 + 699 + 699 KB. This seems really high. Is there any best practice to use pdfWorker? We also see two threads of PDF.Worker in Chrome Console Memory tab due to two imports. 

![image](https://user-images.githubusercontent.com/4205770/106582666-19f43080-64f9-11eb-935c-ac46652097c7.png)

![image](https://user-images.githubusercontent.com/4205770/106581606-e533a980-64f7-11eb-89da-830bd4d0fef1.png)

![image](https://user-images.githubusercontent.com/4205770/106581312-9423b580-64f7-11eb-9bfe-39bfee79fd02.png)

Are others also facing the same issue have a huge bundle size and memory threads?
How can we optimize this?
Can you please help?

**Comment by RBSUS** [comment]
Hi @jinman, I have just come across this issue, I had to set \"GENERATE_SOURCEMAP=false\ in my build script to even get my project to build. I am going to look further into slimming down the bundle size significantly. Did you make any progress on this?
