### ISSUE TITLE
Load whole pdf document and provide search

### ISSUE THREAD

**Issue by boulderx** [agentcooper/react-pdf-highlighter#117]
Hi,

is it possible to load the the whole document and not only the visible parts? 
I'm asking because I want to be able to search (for example via simple browser search)
in the whole document. I think currently the search results are only displayed for the loaded pages
as expected.

**Comment by ChrisSabau** [comment]
I was able to create a search bar by utilizing the pdfjs PDFFindController search method:

`
this.pdfFindController.executeCommand("find" + type, {
query: searchText,
phraseSearch: true,
caseSensitive: false,
entireWord: false,
highlightAll: true,
findPrevious: false });
`

You would need to create an instance of pdfFindController - `this.pdfFindController = new PDFFindController({ linkService: this.linkService })`
Then add this.pdfFindController  to the viewer

Don't forget to import PDFFindController from "pdfjs-dist/web/pdf_viewer"

That's how I got search to work. Now you can get crazy with it and add features like match whole word or match case etc...

Let me know if you want more details.

**Comment by boulderx** [comment]
Thanks @ChrisSabau that was exactly what I was looking for!
