### ISSUE TITLE
Manual zooming reverts back to auto

### ISSUE THREAD

**Issue by hungriesthippo** [agentcooper/react-pdf-highlighter#118]
I'm using zoom in/out buttons on a PDF in an iframe. The zoom changes are quickly reverting back to `auto` (i.e. zooming back out).

I believe the issue is the `resizeObserver` introduced in #79, but I'm not sure why that is firing without the containing div actually changing in size.

**Comment by c3founder** [comment]
Having the same issue upgrading from 3.1.0 to 3.4.0 

Any way to fix this?

**Comment by codiejay** [comment]
How did you implement the zooming in and out in the first place, please.
