### ISSUE TITLE
pdfjs.worker not found when using with webpack

### ISSUE THREAD

**Issue by AdrianLsk** [agentcooper/react-pdf-highlighter#12]
Hi, I am trying to use your library with webpack, but unfortunately I am getting an error due to webpack not able to find a path to pdf.worker.

```
0.dll.js:1 Uncaught ReferenceError: webpackJsonp_name_ is not defined
    at 0.dll.js:1
```

The source.js looks like

```webpackJsonp_name_([0],{

/***/ "./node_modules/pdfjs-dist/build/pdf.worker.js":
/***/ (function(module, exports, __webpack_require__) {

eval("/* WEBPACK VAR INJECTION */ ...
/***/ })

})
```
I found this [thread](https://github.com/mozilla/pdf.js/issues/7612), but don't have enough experience to fix it myself. 

Any idea how to make it work?

**Comment by mapreal19** [comment]
Hi @AdrianLsk this may be fixed here: https://github.com/agentcooper/react-pdf-annotator/pull/11/files#diff-24ebce9f5f499b23e2389ef8738e8a90R7

**Comment by sudarshanshenoy** [comment]
@AdrianLsk I was facing a issue when i used webpack4. I had to update the pdf js. take a look at this https://github.com/agentcooper/react-pdf-highlighter/pull/42
