### ISSUE TITLE
Area highlight: colored border instead of fill overlay

### ISSUE THREAD

**Issue by tfiers** [agentcooper/react-pdf-highlighter#121]
Great project!

Idea for an option: when highlighting an area, I would prefer just a border to show the annotation, instead of the yellow fill overlay. I think it would look cleaner (my use case is subpanels in figures of academic papers).

I come from https://github.com/c3founder/Roam-Enhancement btw, which uses react-pdf-highlighter.

Related, is this low resolution problem known?
Extracted area image:
![image](https://user-images.githubusercontent.com/3773558/112133130-43f5d500-8bc3-11eb-9714-dc7ed2d2cb1b.png)
The original for reference:
![image](https://user-images.githubusercontent.com/3773558/112133171-5112c400-8bc3-11eb-9384-27c19933b115.png)

**Comment by zhl5317** [comment]
Hi @tfiers , Did you solve this problem later

**Comment by cyogian** [comment]
Apply these css properties:

.AreaHighlight > .AreaHighlight__part {
// this is a css selector for all AreaHighlight components
     background-color: rgba(0,0,0,0); //this will give fully transparent color to background
     border: 1px dashed blue; //set border as per your requirement
}
