### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by bhagujava** [agentcooper/react-pdf-highlighter#125]
/Users/bhargavpatel/Downloads/react-pdf-highlighter-master/node_modules/pdfjs-dist/lib/display/api.js 1885:137
Module parse failed: Unexpected token (1885:137)
File was processed with these loaders:
 * ../../node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       numPages: this._numPages,
|       annotationStorage: (annotationStorage === null || annotationStorage === void 0 ? void 0 : annotationStorage.getAll()) || null,
>       filename: ((_this$_fullReader = this._fullReader) === null || _this$_fullReader === void 0 ? void 0 : _this$_fullReader.filename) ?? null
|     }).finally(() => {
|       if (annotationStorage) {

**Comment by vidhyazworld** [comment]
Same for me any solution?

**Comment by bhagujava** [comment]
@vidhyazworld I found it actually issue is with pdfjs-dist lib. The stable release is not working.

Use ````"pdfjs-dist": "2.6.347",```` and remove ````^```` from version

**Comment by fpaupier** [comment]
@bhagujava Thanks, this fixed the compilation. 

However, the .pdf doesn't appear anymore in the right pane when running the example from the repo with `npm start`. No error message, nor warning in the console. Did you encounter this issue too?

**Comment by AlexeyGorobtsov** [comment]
@bhagujava  
1 step fix version "pdfjs-dist": "2.6.347"
2 step run npm install in root dir "react-pdf-highlighter

**Comment by vidhyazworld** [comment]
@bhagujava  Thanks a lot that fixed the issue. Do you know how to save pdf with text highlighted in it. If so please share your knowledge on it.

**Comment by ChrisSabau** [comment]
@vidhyazworld This doesn't modify the pdf in anyway.

**Comment by agentcooper** [comment]
Version 4.0.0 should fix this.

**Comment by cyogian** [comment]
> Use `"pdfjs-dist": "2.6.347",` and remove `^` from version

This is not working for me.

**Comment by bottxiang** [comment]
Try this `import file from './x.pdf';`
```
import React, { useState } from 'react';
import { Document, Page } from 'react-pdf';
import file from './x.pdf';
export default function MyApp() {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  return (
    <div>
      <Document
        file={file}
        onLoadSuccess={onDocumentLoadSuccess}
      >
        <Page pageNumber={pageNumber} />
      </Document>
      <p>Page {pageNumber} of {numPages}</p>
    </div>
  );
}
```
