### ISSUE TITLE
How to color an AreaHighlight upon selection?

### ISSUE THREAD

**Issue by fpaupier** [agentcooper/react-pdf-highlighter#127]
# Current situation
Text highlights or simply Highlight, which are components from `Highlight.js`, appear in red when you select them until you scroll and then there's a 0.3 seconds transition to the original background color (yellow in the demo).  

Unfortunately, this doesn't work for AreaHighlights (components from `AreaHighlight.js`). They're not colored upon selection, they remain yellow.

![2021-04-15 12 33 01](https://user-images.githubusercontent.com/29223998/114855941-c51d4200-9de6-11eb-8c13-6c6a9d08f445.gif)

# Desired behavior
I'd like to have the `AreaHighlights` colored upon selection like we have for `Highlight`. In a page with multiple `AreaHighlights`, having a special color applied upon selection - just like what we have for `Highlight` - would be very helpful to speed up information retrieval in a pdf.

# Attempts
I took a look at what is done for an `Highlight` in hope of emulating it for an `AreaHighlight`.

I looked at `src/style/Highlight.css` and found that an `Highlight` with the class name extension of `--scrolled-to` is rendered with a red background color.
```css
/* src/style/Highlight.css */
.Highlight--scrolledTo .Highlight__part {
  background: #ff4141;   /* red */
}
```

Setting this className is straightforward in `Highlight`; when looking at `/src/components/Highlight.js`, we use the prop `isScrolledTo` to determine the class name: (`...` is used for ellipsis )
```jsx
class Highlight extends Component<Props> {
  render() {
    const {
      position,
      ...
      isScrolledTo
    } = this.props;

    const { rects, boundingRect } = position;

    return (
      <div
        className={`Highlight ${isScrolledTo ? "Highlight--scrolledTo" : ""}`}
      >
       ...
      </div>
    );
  }
}

```

So I did the same thing for an `AreaHighlight` in `src/components/AreaHighlight.js` and added an additional `prop` for `isScrolledTo`:

```jsx
type Props = {|
  highlight: T_ViewportHighlight,
  onChange: (rect: T_LTWH) => void,
  isScrolledTo: boolean  // New
|};

class AreaHighlight extends Component<Props> {
  render() {
    const { highlight, onChange, isScrolledTo, ...otherProps } = this.props;  // extract isScrolledTo prop
    return (
      <div className={`AreaHighlight ${isScrolledTo ? "AreaHighlight--scrolledTo" : ""}`}> // use isScrolledTo for classname selection
        <Rnd
          className={`AreaHighlight__part`}
          ...
        />
      </div>
    );
  }
}
```

Ultimately, I also updated the css of `/src/style/AreaHighlight.css` to have a different styling upon `AreaHighlight` selection:
```css

.AreaHighlight__part {
  cursor: pointer;
  position: absolute;
  background: rgba(255, 226, 143, 1);
  transition: background 0.3s;
}

.AreaHighlight--scrolledTo .AreaHighlight__part {
  background: #ff4141;
}

```

## Why this does not work?

When running the example project, I noticed that the `isScrolledTo` prop is always `undefined` in my `AreaHighlight` component. I don't understand what I should do to pass `isScrolledTo` to this component as we do for a plain `Highlight`. I suppose the answer is somewhere in `src/components/PdfHighlighter.js` but couldn't find what I should to differently for an `AreaHighlight` compared to an `Highlight`.

Any thoughts @agentcooper ?

------

# Edit
I found a solution and proposed a PR #129 to address it. 

Result looks great!
![2021-04-19 13 53 14](https://user-images.githubusercontent.com/29223998/115232078-9ff63f80-a116-11eb-9d13-84d12205d911.gif)

(_In my initial issue, I just forgot to update client code of the example `App.js`  and pass the `isScrolledTo` prop to an `AreaHighlight` component_)

**Comment by agentcooper** [comment]
Done in #129, released in 4.0.0.
