### ISSUE TITLE
Unexpected token compiler error

### ISSUE THREAD

**Issue by xb-developer** [agentcooper/react-pdf-highlighter#147]
Good morning, I'm running into a compiler issue:  `./node_modules/react-pdf-highlighter/node_modules/pdfjs-dist/lib/display/api.js 1926:137
Module parse failed: Unexpected token (1926:137)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       numPages: this._numPages,
|       annotationStorage: (annotationStorage === null || annotationStorage === void 0 ? void 0 : annotationStorage.serializable) || null,
>       filename: ((_this$_fullReader = this._fullReader) === null || _this$_fullReader === void 0 ? void 0 : _this$_fullReader.filename) ?? null
|     }).finally(() => {
|       if (annotationStorage) {`

when I try to import only the example folder in my project and then running "npm install react-pdf-highlighter".  Any hints on what could the problem be? Thanks

**Comment by Vagizova** [comment]
Hi! did you solve this?

**Comment by agentcooper** [comment]
Should be fixed by version `5.1.0`.
