### ISSUE TITLE
Support SSR users

### ISSUE THREAD

**Issue by brillout** [agentcooper/react-pdf-highlighter#149]
Author of [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) here. One of my users is trying to use `react-pdf-highlighter` in an SSR context.

But they have problems because `react-pdf-highlighter` doesn't properly resolve on the server-side, see https://github.com/stephensamra/vite-ssr-pdf-issue.

**Comment by agentcooper** [comment]
Hi @brillout, do you have any pointers on providing support for this?
