### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by Vagizova** [agentcooper/react-pdf-highlighter#159]
Hi! Could you make some of the fields optional? For example, if I need only highlight the text I need to provide extra information that I don't have: 
```
comment: {
  text: '',
  emoji: ''
},
content: {
  text: ''
}
```

so maybe it is ok to make comments & content optional? or at least Emoji... What do you think? 

and also Q: Should enableAreaSelection be boolean? now enableAreaSelection={() => false}  or can you provide something else to disable area selection at all?

**Comment by agentcooper** [comment]
Yes, it makes sense. I would gladly accept a PR that makes those fields optional. You can find the type annotation here:
https://github.com/agentcooper/react-pdf-highlighter/blob/3d7a390f1603d1190c4b7d35cca4d9c66f271a17/src/types.ts#L43-L46

For the second question passing `() => false` should indeed disable the area selection. Let me know if this is not the case.

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;
