### ISSUE TITLE
Adding area will cause many highlights to move down

### ISSUE THREAD

**Issue by zhl5317** [agentcooper/react-pdf-highlighter#160]
Adding rectangular highlights will cause other highlights move down

![image](https://user-images.githubusercontent.com/17403033/135413788-58b6c285-faf1-4db9-b509-254439f72547.png)

**Comment by zhl5317** [comment]
> Any update on this?

AreaHighlight.css

Comment out “ border: 1px solid #333;” code will works

```
.AreaHighlight {
  /* border: 1px solid #333; */
  background-color: rgba(252, 232, 151, 1.0);
  opacity: 1;
  mix-blend-mode: multiply;
} 

```

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by dwayneyuen** [comment]
> > Any update on this?
> 
> AreaHighlight.css
> 
> Comment out “ border: 1px solid #333;” code will works
> 
> ```
> .AreaHighlight {
>   /* border: 1px solid #333; */
>   background-color: rgba(252, 232, 151, 1.0);
>   opacity: 1;
>   mix-blend-mode: multiply;
> } 
> ```

This didn't fix the issue for me :(
