### ISSUE TITLE
Support for OptionalContentConfig in PdfHighlighter

### ISSUE THREAD

**Issue by nikhilag** [agentcooper/react-pdf-highlighter#161]
In order to allow seeing PDF layers and toggling them on/off, I am wondering what would be the best way to add support for OptionalContentConfig in this library. See https://github.com/mozilla/pdf.js/issues/269#issuecomment-669282999 for reference.
@agentcooper Please suggest what would be the best way. Also thanks for this great library!

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;
