### ISSUE TITLE
Way to Turn Highlighting Off?

### ISSUE THREAD

**Issue by jmripper** [agentcooper/react-pdf-highlighter#162]
Hi there,

Is there a way to view highlights and the pdf but turn highlighting on and off for the whole document?

I looked over the code and docs and didn't see anything.

Thanks!

**Comment by agentcooper** [comment]
Maybe create a boolean state in your app and don't pass the highlights to the PdfHighlighter component if the flag is turned off.

Something like:
```jsx
highlights={shouldRenderHighlights ? highlights : []}
```
instead of:
https://github.com/agentcooper/react-pdf-highlighter/blob/3d7a390f1603d1190c4b7d35cca4d9c66f271a17/example/src/App.tsx#L224
