### ISSUE TITLE
Access to PDF.js functionalities

### ISSUE THREAD

**Issue by Brenw10** [agentcooper/react-pdf-highlighter#165]
Hey guys, I am trying to access PDF.js functionalities, is it possible?
For example, I want to display for the user the Outline contents (catalogue).
How can I have access to it?

Also, can I move the user to a page dynamically?
Or even show only one page and show add next and back buttons?

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;
