### ISSUE TITLE
Question about saving highlights

### ISSUE THREAD

**Issue by justinmoon** [agentcooper/react-pdf-highlighter#168]
Thanks for the great library.

I'm trying to store links to PDF highlights in markdown like this: `[description](filename.pdf?t=<top>&r=<right>&l=<left>&b=<bottom>&p=<page>)`. What should I actually store?

The `Scaled` type that is passed to `onSelectionFinished` callback of the `PdfHighlighter` component is pretty verbose and it seems scaled to my current resolution? Seems like it would be more concise to store unscaled position? Also, what is the purpose of the `Scaled.boundingRect`? I would prefer to just store one rectangle to be more concise ... so it seems like `boundingRect` might be better to store than all the `rects` ...

This is the [scrollTo](https://github.com/agentcooper/react-pdf-highlighter/blob/10e440cbfefaffbbc301a9d2a840dcc2b2030151/src/components/PdfHighlighter.tsx#L437) callback

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;
