### ISSUE TITLE
Trouble implementing PDFFindController from PDFJS

### ISSUE THREAD

**Issue by RutgerSwirski** [agentcooper/react-pdf-highlighter#169]
Hey guys,

I am currently using the react-pdf-highlighter package and I would like to add a search functionality throughout the PDF documents, however I am really having a hard time trying to implement the pdfFindController from pdfjs, I saw someone else managed to get it working with this package, could anyone please tell me how to implement this? 

I am trying to add a new pdfFindController to an already existing pdfViewer instance using the eventBus and linkService i get from window.PDFViewer that is created by react-pdf-highlighter but no success. Any help would be appreciated!

Thanks!

**Comment by dalbir** [comment]
Hi @RutgerSwirski 

You can use following code in init()  function:

`this.viewer.findController= new PDFFindController({
      eventBus: this.eventBus,
      linkService: this.linkService,
    });`

**Comment by holub008** [comment]
See discussion in https://github.com/agentcooper/react-pdf-highlighter/issues/176 for adding this to API.

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;
