### ISSUE TITLE
Collaboration with polar-bookshelf

### ISSUE THREAD

**Issue by burtonator** [agentcooper/react-pdf-highlighter#17]
Afternoon.

I'm the author of polar-bookshelf... 

and I thought it might make sense to introduce myself and see if we can collaborate on PDF annotation:

https://github.com/burtonator/polar-bookshelf

The goals of Polar are pretty ambitious. It started out as a set of scripts for managing my growing pile of books and research papers that I was reading and is now more of a larger product around web annotation starting as an Electron app.

Right now we have a beta release and another bit beta due out early next week.

The big change is that we're adding support for HTML by capturing pages and rendering them locally.  

I'm probably going to migrate everything to React + Redux.  Internally this is sort of the model I wanted to go with but I didn't think this was going to be a large project at the time.

Right now one of the biggest challenges we have is with the annotation component. I'd like to support a rich annotation model including comments, pagemarks, bookmarks, notes, flashcards, icons, etc.  

We're still refactoring the code and initially I didn't want to go with react-pdf-highlighter because it used react and I didn't want to swallow using a framework.  But it might make sense to since we're going in that direction anyway.

**Comment by mapreal19** [comment]
@burtonator I'll be happy to collaborate on this too. I've been using a fork of this project in a web app I'm working on. I was interested on extracting highlights from a PDF. Example: 

![pdf-highlighter](https://user-images.githubusercontent.com/3055997/42557075-c5510d2a-84ed-11e8-8d0f-26133159b0c0.gif)

I think it'll make sense if we combine efforts to have this project as the base for everyone to use. But don't know how busy @agentcooper will be.

**Comment by agentcooper** [comment]
@burtonator I don't work much on the project these days, however I am happy to accept PR's and help with some new features.

@mapreal19 Let me know if there is something that forces you to fork. We can add more options to control some of the behavior.

**Comment by mapreal19** [comment]
@agentcooper ok I think I could bring some of my suggested changes in small PRs, so we can discuss each of them separately

**Comment by burtonator** [comment]
@mapreal19 Looks awesome... want to reach out to me via email ... burton ... at ... inputneuron.io or we could discus collaboration as an issue here:

https://github.com/burtonator/polar-bookshelf

**Comment by mapreal19** [comment]
@burtonator would it make sense for you to get the basics in this project here first? In a way you could reuse this in your project. I don't have much time but I'll try to make improvements here, focusing first in text highlighting

**Comment by Farbod29** [comment]
dear guys I want to combine my recommender system with this pdf highlighter, my front end project is start with
` npx create-react-app`
 I think I have JS version problem . here cannot detect props / type var my syntax totally different to this project ....Anyone know how to solve it. I install all dependencies like


 l**odashpdfjs-   distreact-    pointablereact-   rnd**

![screenshot 2018-07-29 21 49 23](https://user-images.githubusercontent.com/17232450/43370127-c80c02fa-9379-11e8-83c1-18d24731f2f5.png)

please write here if you know the answer. thanks
