### ISSUE TITLE
Trouble importing components and types 

### ISSUE THREAD

**Issue by mahdigb05** [agentcooper/react-pdf-highlighter#171]
Hey guys,

I was using an old version and followed the example provided to use the lib.
today I updated to the latest version but I have some difficulties importing the components and the types.

![image](https://user-images.githubusercontent.com/46164393/150992448-117c0fcc-293e-48c9-bebb-698f142df7cd.png)

a little help would be very appreciated.
Thanks.

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;
