### ISSUE TITLE
Multi-page highlight infinite loop error - Issue (and solution)

### ISSUE THREAD

**Issue by OscarBC** [agentcooper/react-pdf-highlighter#172]
Hello! 

I found out an issue (and its solution) while debugging in an iOS simulator. [I was also able to replicate it in the demo page.](https://streamable.com/0xnlgx)

The error appears when selecting more than two pages and causes the web app to become unresponsive because of an infinite loop. 

The solution is to increment the currentPageNumber in the libs/pdfjs-dom.ts [getPagesFromRange function.](https://github.com/agentcooper/react-pdf-highlighter/blob/a9722afdf37c8ecc16b67743f611024b669f6c87/src/lib/pdfjs-dom.ts#L56)

```
while (currentPageNumber <= endPage.number) {
    const currentPage = getPageFromElement(document.querySelector('[data-page-number='${currentPageNumber}'') as HTMLElement );
    if (currentPage) {
      pages.push(currentPage);
    }
    **currentPageNumber++;**
  }

```

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;
