### ISSUE TITLE
Gaps in Multiline Highlights

### ISSUE THREAD

**Issue by holub008** [agentcooper/react-pdf-highlighter#180]
## Bug

The middle rectangles of multiline highlights are not being passed from the `onSelectionFinished` prop in Firefox. The end result in the demo app looks like:

<img width="1676" alt="Screen Shot 2022-03-22 at 4 00 31 PM" src="https://user-images.githubusercontent.com/7282590/159575101-13d57871-1ade-4543-a24c-4722ae72ebe4.png">
<img width="1680" alt="Screen Shot 2022-03-22 at 4 01 05 PM" src="https://user-images.githubusercontent.com/7282590/159575226-b88d6d73-ce79-4d8a-9cea-62caea168aa5.png">

## Reproduce

In Firefox, go to the demo app and make a 3+ line selection among the plain text, and click "Add Highlight".

Myself and several others have verified this bug in our target application & the example app, using several different PDFs. I believe this bug first appeared in the 5.4.0 release.

**Comment by holub008** [comment]
The bug doesn't reside there, but the middle highlight rects are being filtered out in `getClientRects`, where the `isClientRectInsidePageRect` check is failing. In the below example, the middle highlights have a right extent of 1144.51, while the page container has a right extent of 1143.25. I added some fudge pixels to generate the attached visual:

```js
const isClientRectInsidePageRect = (clientRect: DOMRect, pageRect: DOMRect, fudge: number=2) => {
  if (clientRect.top < (pageRect.top - fudge)) {
    return false;
  }
  if (clientRect.bottom > (pageRect.bottom + fudge)) {
    return false;
  }
  if (clientRect.right > (pageRect.right + fudge)) {
    return false;
  }
  if (clientRect.left < (pageRect.left - fudge)) {
    return false;
  }

  return true;
};
```

The highlighted client rects sure look wrong, and they're coming directly from PDF.js's `range.getClientRects` method. So I'm led to believe this is a platform-dependent behavior (bug) of PDF.js. Ironic that it's coming from a Mozilla project :D

<img width="1382" alt="Screen Shot 2022-03-23 at 12 40 32 AM" src="https://user-images.githubusercontent.com/7282590/159631530-f6ccd670-29b4-4318-a4ab-2f6b882839f6.png">

**Comment by holub008** [comment]
Although I don't understand its implications, this behavior seems to be driven by `textLayerMode: 2` for the `PDFViewer`, which was introduced in https://github.com/agentcooper/react-pdf-highlighter/pull/170. When I switch the mode between 1 & 2, the selection experience is better in 2 because it appears to add some margin to the left & right of each line, creating a larger selection region; I wonder if that added margin is leaking through to our highlight areas (in FF only?).

I don't have the understanding or time to dig into PDF.js internals so would advocate for a fix/hack at our level. IMO, it's preferable to have extra chunky looking highlight regions over gaps. The former is visually unpleasing while the latter appears outright incorrect. Is it worth adding a few fudge pixels to our `isClientRectInsidePageRect` check to allow these to pass through?

**Comment by OscarBC** [comment]
Hello @holub008, I've made the PR #181  to upgrade to the latest pdfjs-dist package and the issue you are presenting seems to be resolved. Feel free to download my branch and test it :) 

See screenshots: 

![Captura de Pantalla 2022-03-23 a la(s) 17 11 52](https://user-images.githubusercontent.com/5251988/159811813-e3e8d229-d9bd-4e09-a2a8-70e6c96949d1.png)
![Captura de Pantalla 2022-03-23 a la(s) 17 15 09](https://user-images.githubusercontent.com/5251988/159811817-2a985c66-0b13-4acd-b01c-32e76793f735.png)

**Comment by agentcooper** [comment]
@OscarBC Hey Oscar, I still see the issue in Firefox (98.0.2) on your branch:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/794591/159967481-9ae93bea-c79c-4b88-8c83-17bb2380e9b6.png">

I am selecting starting from "However," (right under the third default highlight) till "false positives." (end of page).

**Comment by OscarBC** [comment]
I'm working on new fixes. [One of them is changing the parent container of the highlights.]   (https://github.com/OscarBC/react-pdf-highlighter/commit/beecb7d2bfde41ec83561b1372f19d9a70d48bb6#diff-aad0d8f3d2a25f056246f9a7fc110687bb21754a281288bba27ee4337a3b354f) I face some issues when zooming in on the document that caused the highlights position to move (similar the issue you are having on firefox). 

See if the these changes fix your issues, the branch is: https://github.com/OscarBC/react-pdf-highlighter/tree/fix/zoom-highlghlights-tips-fixes If you would like to test them out.

----

This is a video of the issue:

https://user-images.githubusercontent.com/5251988/159976800-40ced908-c509-4285-97cc-d98a5cd893a0.mov

This is a video after the fix:

https://user-images.githubusercontent.com/5251988/159976843-238c2e04-b2eb-492a-a9ab-b57e3e81aff6.mov

**Comment by holub008** [comment]
@OscarBC Thanks for digging in! It's hard to tell from your screen grabs if you did this in all your testing, but you have to click "Add Highlight" to trigger the gaps. I did a fresh checkout/install on your PR's branch and did not have luck with the "However" -> end of page highlight.

**Comment by OscarBC** [comment]
ohh I hadn't clicked on it, hehe. Let me see what I can find.

**Comment by OscarBC** [comment]
@holub008 I think setting **textLayerMode: 1,** in the PdfHighlighter.tsx class, for the PDFViewer constructor options make this issue go away. 

I tried debugging it, and it all has to do with the ranges and their transformation from the viewport, but it's hard to debug it. All those calculations which @agentcooper implemented are based on the viewport that come from pdf-js.

**Comment by holub008** [comment]
Yep, I noticed the same. I'm not sure that's the way to go here, however, as the text selection felt degraded with mode=1 (less margin on the side to start your selection).

**Comment by marcelodlr** [comment]
Basically PDF.js has a very old bug that when `textLayerMode: 1`, the text selection selects the entire page when hitting a white space ([link to bug](https://github.com/mozilla/pdf.js/issues/9843)). They released a enhanced selection mode, using `textLayerMode: 2`, but this mode has problem with regards to getting the text selection bounds since youll be getting bounds that are nor within the text's area. ([link](https://github.com/mozilla/pdf.js/issues/9843#issuecomment-1030720809))

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by OskarKaminski** [comment]
> IMO, it's preferable to have extra chunky looking highlight regions over gaps. The former is visually unpleasing while the latter appears outright incorrect.

@holub008 maybe we don't have to make a value judgement here. All that I would see as satisfacing is to expose to the clients ability to provide own recs filtering function.

Then everyone can provide their own implementation fitting own use cases and supported browsers.
Would you be interested in PR with that proposition?
