### ISSUE TITLE
Change the Color of highlighter

### ISSUE THREAD

**Issue by mark7588** [agentcooper/react-pdf-highlighter#182]
Is there any way to change the color of highlighter dynamically?
I have been inspecting codes to apply to my project but I could not find any styling element that sets the color of the highlighter.

**Comment by OscarBC** [comment]
Check the "./src/style/" files there you'll find the css classes for ".textLayer ::selection" and ".Highlight_part", which sets the highlight color. During selection, and rendering the highlights

**Comment by mark7588** [comment]
Thanks for letting me know. 
I am little confused since I have those files in the node_module 
In the project, I imported this source code as node_module 
and integrate example_code file into my project folder. 
Does that mean I need to change style file in the node_module/react-pdf-highlighter?

**Comment by OscarBC** [comment]
You should define that style in your project, if you implemented the example_code you should have something like the /styles/App.css, there should be a good place to override the default style. In whatever class you implemented the react-pdf-highlighter. 

I wouldn’t recommend you to make any changes inside node_modules since those files are managed by npm and your changes can easily be lost.

**Comment by mark7588** [comment]
I've tried with different approaches but they all failed... 
The followings are what I tried:
1. Change the CSS style code in node_modules: does not have any effect on color
2. Import components from node_module and import components from my own local folder --> same result as 1
3. Apply style to the imported Highlight component by adding specific className to the component --> same result as 1 
Thanks so much for helping me!

**Comment by sarcXD** [comment]
you could probably do what I did, and say, make a separate folder for the library, clone the project there and install it to set it up. Not exactly the cleanest solution, but if nothing else works this would. You could then make any changes you require.
How viable this is depends on your use case, but if nothing else works, this would.

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by Grabdone** [comment]
There is no need for cloning the project. You just need to copy the below files to your project, you will find these files in your node modules. 
<img width="260" alt="Screenshot 2022-07-27 at 4 09 12 PM" src="https://user-images.githubusercontent.com/36327928/181232945-43d4486a-9d59-4e70-b3de-eb955fdb0185.png">
import these files where you are using the PdfHighlighter component like this 
`import "./style/AreaHighlight.css";
import "./style/Highlight.css";
import "./style/Highlighter.css"
import "./style/MouseSelection.css";
import "./style/pdf_viewer.css";
import "./style/Tip.css";`
