### ISSUE TITLE
Unlock `pdfjs-dist` library version

### ISSUE THREAD

**Issue by andrewmiroshnichenko** [agentcooper/react-pdf-highlighter#188]
Thanks for the cool library!
We are using it extensively in our project, along with other one [react-pdf](https://github.com/wojtekmaj/react-pdf)

We noticed that both libraries use `pdfjs-dist` package, with locked version. And, because these versions aren't the same - we have `pdfjs-dist` included two times into our production bundle.

Can't `pdfjs-dist` version for [react-pdf-highlighter](https://github.com/agentcooper/react-pdf-highlighter) be unlocked by the chance?

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by andyryan** [comment]
I've now encountered this same issue, however it is completely stopping PDFs from rendering using this library. The error handler returns the following error:

> The API version "2.8.335" does not match the Worker version "2.4.456"."

Upon exploring the package-lock.json, I can see that 2.4.456 is the version of pdfjs-dist in the dependencies of react-pdf, and 2.8.335 is the dependency of react-pdf-highlighter

**Comment by agentcooper** [comment]
I think there are some issues with the current major version of pdfjs-dist. I would happily land a PR that makes it work with pdfjs-dist 3.

**Comment by andyryan** [comment]
I did manage to work around this by putting the following in my package.json
```
"overrides": {
        "react-pdf": "5.7.0",
        "pdfjs-dist": "2.16.105"
    },
```

I'm not sure if it was the `react-pdf` or `pdfjs-dist` override or a combiantion of both which got me past my issue eventually.
