### ISSUE TITLE
position object missing rectangles not visible in the viewport

### ISSUE THREAD

**Issue by marcelodlr** [agentcooper/react-pdf-highlighter#190]
Hi Folks, 

I have found an issue when highlighting a text across multiple pages where some lines of text are excluded from the highlight.

Debugging the `onSelectionFinished` function, the `content` attribute has the correct text, but the `rects` array in the position object is missing some rectangles. 

I've recorded a loom video showing the error. I've been able to reproduce on both 5.3.0 and 5.4.0

https://www.loom.com/share/4c62f348667243baac484e3ff9425afe

**Comment by marcelodlr** [comment]
More information about the issue:

I believe the error is in the `getClientRects` function. Because when we get the pageRect using ` const pageRect = page.node.getBoundingClientRect();` the top and bottom from the pageRect are relative to the viewport. So if there are highlighted words not visible, the `isClientRectInsidePageRect(clientRect, pageRect)` returns false.
```
for (const clientRect of clientRects) {
    for (const page of pages) {
      const pageRect = page.node.getBoundingClientRect();

      if (
        isClientRectInsidePageRect(clientRect, pageRect) &&
        clientRect.top >= 0 &&
        clientRect.bottom >= 0 &&
        clientRect.width > 0 &&
        clientRect.height > 0 &&
        clientRect.width < pageRect.width &&
        clientRect.height < pageRect.height
      ) {
        const highlightedRect = {
          top: clientRect.top + page.node.scrollTop - pageRect.top,
          left: clientRect.left + page.node.scrollLeft - pageRect.left,
          width: clientRect.width,
          height: clientRect.height,
          pageNumber: page.number,
        } as LTWHP;

        rects.push(highlightedRect);
      }
    }
  }
```

![rph_error](https://user-images.githubusercontent.com/3401226/170712795-4ce71b34-75ec-45c0-9310-c71e0eb5b7c8.gif)

This GIF shows the problem: When I highlight those 2 lines, and both of them are visible (are within the viewport), the comment dialog opens with both highlight rectangles. 
When I select both lines, and only the second one is visible, the comment dialog opens with only the visible line highlighted (It excludes the first line because it is outside of viewport).

**Comment by marcelodlr** [comment]
#191

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by QhdJiaYou** [comment]
Why does TipComponent popup twice in the first video? I still have this problem now, the version is 7.0.0
