### ISSUE TITLE
react-pdf-highlighter not working with react-doc-viewer.

### ISSUE THREAD

**Issue by Grabdone** [agentcooper/react-pdf-highlighter#199]
I was using "react-doc-viewer" in my app. Using react-pdf-highlighter, I was not able to render the pdf. I commented out 
import DocViewer from "react-doc-viewer"; in my code to make make react-pdf-highlighter work.

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;
