### ISSUE TITLE
Right click is disabled

### ISSUE THREAD

**Issue by acco** [agentcooper/react-pdf-highlighter#20]
Thanks for the wonderful tool!

It appears this disables right-clicking anywhere on the page where a PDF is loaded (see demo). Is this intentional? Would be great to retain right-click support outside of the PDF document.

Best,
Anthony

**Comment by agentcooper** [comment]
Thanks! Definitely not intentional. Probably the `return` in [this condition](https://github.com/agentcooper/react-pdf-highlighter/blob/master/src/components/PdfHighlighter.js#L447) is the offender.

**Comment by acco** [comment]
@agentcooper Hmm ... just tested with that commented out, no fix. I'll keep hunting

**Comment by acco** [comment]
Ah - found it! This is definitely the offender:

https://github.com/agentcooper/react-pdf-highlighter/blob/master/src/components/PdfHighlighter.js#L142

I assume your intent was just to disable right-clicks in the PDF? I believe capturing all `onMouseDown` inside PdfHighlighter (and `e.preventDefault()`) will do the trick

**Comment by acco** [comment]
Playing with this right now - I think this has the effect you were going for:

https://github.com/acco/react-pdf-highlighter/commit/5a9b5ab892265bc123b6e8ae1518f9863967e626

**Comment by agentcooper** [comment]
Makes sense. Send a PR?
