### ISSUE TITLE
Text selection and copy feature

### ISSUE THREAD

**Issue by susylPearl** [agentcooper/react-pdf-highlighter#201]
How can we select the text from PDF viewer content and perform copy action, so that we can paste that copied text on anywhere that we wants. Now, the context-menu is disabled, any suggestions would be appreciated.

**Comment by muditmahajan21** [comment]
This would be a useful thing to have. Any update if you or someone got it working?

**Comment by NathanHam16** [comment]
+1

**Comment by stanleyAtYL** [comment]
+ 1

**Comment by Rasfuranku** [comment]
@agentcooper did this get implemented?

**Comment by Crashillo** [comment]
Apparently in `8.0.0-rc.0` does not work yet: https://agentcooper.github.io/react-pdf-highlighter/

**Comment by Crashillo** [comment]
Regarding the context-menu, it was disabled in this line, any reason?

https://github.com/agentcooper/react-pdf-highlighter/blob/4a65c282a76915d4ff3e53d11be15b8b56d50ffe/src/components/PdfHighlighter.tsx#L565
