### ISSUE TITLE
After React 16 to React 18 version migration getting Error 

### ISSUE THREAD

**Issue by sadashiv-sumasoft** [agentcooper/react-pdf-highlighter#202]
WARNING in ./node_modules/react-pdf-highlighter/dist/esm/lib/pdfjs-dom.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'D:\projects\updateui\node_modules\react-pdf-highlighter\src\lib\pdfjs-dom.ts' file: Error: ENOENT: no such file or directory, open 'D:\projects\updateui\node_modules\react-pdf-highlighter\src\lib\pdfjs-dom.ts'

I have tried react-pdf-highlighter "^4.0.0" and "^5.4.0" versions.
I am using  React 18, CRA 5 version.
Due to this warning we can not even create production build of application.
Any suggestion?

**Comment by Bohan-J** [comment]
Same problem for me. Have you solved it? Or do you find these warning have an influence on the pdf render performance

**Comment by sumitnagra** [comment]
hi sadashiv-sumasoft , I want to work on this issue
