### ISSUE TITLE
Does not work with uploaded PDF

### ISSUE THREAD

**Issue by rybon** [agentcooper/react-pdf-highlighter#205]
When using an uploaded PDF converted to for example base64 the rendering of the PDF fails. Loading that very same PDF via a URL works fine.

I am using this example code from PDF.js to test: https://mozilla.github.io/pdf.js/examples/ Hello World using base64 encoded PDF

The problem is in `PdfLoader.tsx` in the `getDocument` call. Changing `...this.props` to `url` fixed the issue. This ensures it works for both URLs and uploaded or local files.

Alternative: `url.data ? { data: url.data, ...this.props } : { ...this.props }`

**Comment by rybon** [comment]
Also needs a change in `PdfLoader.tsx` `componentDidUpdate` to `this.props.url.data !== url.data`

**Comment by agentcooper** [comment]
Could you please open a PR with this?
