### ISSUE TITLE
Go to a specific page

### ISSUE THREAD

**Issue by AntonioFucinosDeus** [agentcooper/react-pdf-highlighter#206]
hello there!

Is there anyway to make it to scroll to a specific page? We are receiving an "answer" from the backend and they come with a page linked to them, so we want to highlight the text that comes in that answer only in the specified page.

Thank you!

**Comment by polyamakov** [comment]
ooh I'm looking forward to this feature too 👀

**Comment by AntonioFucinosDeus** [comment]
`window.PdfViewer.viewer.currentPageNumber = page`

Seems to work, i'm my case i added that line of code to the onSearch prop in the PdfHighlighter
