### ISSUE TITLE
usePdfCoordinates doesn't work properly

### ISSUE THREAD

**Issue by rybon** [agentcooper/react-pdf-highlighter#207]
The y-position is incorrect when `usePdfCoordinates` is set to `true`.

The fix is changing `src/lib/coordinates.ts` `pdfToViewport` return statement `top: y1,` to `top: viewport.height - y1,`

**Comment by agentcooper** [comment]
Is this the same as https://github.com/agentcooper/react-pdf-highlighter/issues/73 and https://github.com/agentcooper/react-pdf-highlighter/pull/53?

**Comment by rybon** [comment]
I'm not sure. I think so? The yellow rectangles were too far down the pages and this change fixed it reliably. I was using muPDF to generate the coordinates and its output requires `usePdfCoordinates` and this fix.

**Comment by agentcooper** [comment]
Fixed in #244.
