### ISSUE TITLE
"Error: You are using old position format, please update" when selecting across pages

### ISSUE THREAD

**Issue by JonasGruenwald** [agentcooper/react-pdf-highlighter#22]
Hi, thanks for your work on this great library!

I seem to have found a bug that will crash my react app when attempting to select and highlight text across pages.

It's possible to reproduce this in the demo app, it only throws an error in the console in that case though.
For some reason I can only reliably reproduce it in chromium, it does happen in Firefox, but not every time.

Steps to reproduce:

- Visit the demo app https://agentcooper.github.io/react-pdf-highlighter/# in Chrome
- Click "Reset Highlights" (Maybe not necessary)
- Scroll to page 24/25
- Select everything from the two pages in one mouse motion
- Click "Add Highlight"

The chrome console shows this error:

```
Uncaught Error: You are using old position format, please update
    at i (coordinates.js:58)
    at t.scaledPositionToViewport (PdfHighlighter.js:225)
    at PdfHighlighter.js:273
    at Array.map (<anonymous>)
    at f (PdfHighlighter.js:268)
    at t.renderHighlights (PdfHighlighter.js:262)
    at t.<anonymous> (PdfHighlighter.js:501)
    at e.notifyAll (CallbackQueue.js:74)
    at i.close (ReactUpdates.js:57)
    at i.closeAll (Transaction.js:207)
```

When actually adding the highlight now, clicking on it in the sidebar will throw more errors with `You are using old position format, please update` and not scroll to any location. There is also no highlight added to the two pages.

If there is no way to fix this, would there be a way to catch this error somewhere when using the library so I can just output a message telling the user not to select across pages or something?
I don't find it really necessary to allow this anyway, but users might do it and crash the app.

**Comment by agentcooper** [comment]
Hmm, the "Add highlight" popup does not even appear for me in the case of multi-page selection in Chrome. It does appear in Firefox, but after the click the highlight is trimmed to the first page.

**Comment by JonasGruenwald** [comment]
Just an update: If found out why this is happening.
In coordinates.js, there is a check against the bounding box coordinates like so:

```
  if (!scaled.x1) {
    throw new Error("You are using old position format, please update");
  }
```

If the x1 coordinate has the value `0` (number) it is equivalent to `false` of course, so the error gets thrown, so for bounding boxes that have `x1 = 0` (because they cover the very upper left edge of the page) the app mistakenly crashes.

Depending on what the intention here is, this could be fixed by doing a check for `scaled.x1 === undefined` or something like [this](https://stackoverflow.com/questions/31626876/check-if-falsy-except-zero-in-javascript/31626894).
