### ISSUE TITLE
How to get line separator(\n) on multiline highlighted texts?

### ISSUE THREAD

**Issue by slashgk** [agentcooper/react-pdf-highlighter#228]
How to get line separator(\n) on multiline highlighted texts?
When we highlight text in pdf, it all comes in 1 line, how do I know where is the line break?

**Comment by Elon-Mask12** [comment]
facing the same issue. Any luck?

**Comment by zeus-12** [comment]
still not fixed. please approve the pr, or lmk if i should make any changes to that. @agentcooper
