### ISSUE TITLE
Could you please remove @types from dependencies and move it to devDependencies?

### ISSUE THREAD

**Issue by mikhailbartashevich** [agentcooper/react-pdf-highlighter#229]
Could you please remove @types from dependencies and move it to devDependencies?
`"@types/lodash.debounce": "^4.0.6",
    "@types/react": "^16.4.0",
    "@types/react-dom": "^16.4.0"`

**Comment by agentcooper** [comment]
Done https://github.com/agentcooper/react-pdf-highlighter/commit/08d23c8ea67d65c521a333520c965df2e5239120.
