### ISSUE TITLE
A second highlight area is placed wrongly

### ISSUE THREAD

**Issue by z4m0** [agentcooper/react-pdf-highlighter#25]
A second highlight area in the demo is placed in top of the first one.

The following ones are placed on top of the previous one.

**Comment by z4m0** [comment]
It works using position and size instead of default in here:
https://github.com/agentcooper/react-pdf-highlighter/blob/master/src/components/AreaHighlight.js#L43

**Comment by agentcooper** [comment]
Good catch. Want to send a PR?

**Comment by agentcooper** [comment]
Thanks for the contribution!
