### ISSUE TITLE
Angular support?

### ISSUE THREAD

**Issue by donniekerr** [agentcooper/react-pdf-highlighter#26]
Just a question, not an issue.  Can this be leveraged inside an angular app or has anyone re-written it to work in Angular?  Or have you heard of something similar that would work in Angular?

Thanks,
Donnie

**Comment by agentcooper** [comment]
Hi Donnie,

This project uses React as a core dependency. You can create an Angular wrapper component on top, but this will require to pull React as a dependency to your Angular project which is probably not a good idea. What you can do is too experiment with [Preact](https://preactjs.com/) which is only 3kb and in theory this project should be compatible with it.

Feel free to re-open if you have more questions.
