### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by aleksbobic** [agentcooper/react-pdf-highlighter#262]
Hi this project provides exactly the features I need but I see the last time it was updated was 5 months ago. Is this still actively under development or will there be no further updates? 

Thanks for providing a fantastic package! 😄

**Comment by Elon-Mask12** [comment]
Checkout https://github.com/DanielArnould/react-pdf-highlighter-extended

**Comment by aleksbobic** [comment]
Nice thanks for tip! @Elon-Mask12
