### ISSUE TITLE
Availablitity of Documentation

### ISSUE THREAD

**Issue by snh1999** [agentcooper/react-pdf-highlighter#265]
Is there some other documentation for this project exists other than the ones provided in `example` directory? I am having a bit of hard time following those, and it would be hard to understand the full functionality of the built-in classes without diving into the source code. 

Sorry if it is a repeat question (my search didn't show any other question on this topic), Thank you.

**Comment by abachant** [comment]
Did you find any documentation? I can't seem to find any
