### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [agentcooper/react-pdf-highlighter#27]
Hello. 
I installed it and i got a lot of problems with security packages and I ran "npm audit fix" but using url pdf or local pdf file not work.
Could you please debug it, and if is possible try it on windows plataform because i got architecture warns.

**Comment by agentcooper** [comment]
I did a clean install of react-pdf-highlighter in the new project, ran `npm audit` (npm `6.3.0`) and got:

```                                         
found 0 vulnerabilities
 in 26 scanned packages
```

Could you post any logs and errors you've encountered?

**Comment by jfernal** [comment]
Failed on windows 10 and centos 6, not load pdf file.
 (npm 6.3.0) and (node v8.11.3) x64
npm audit:
found 6 vulnerabilities (1 low, 5 moderate) in 17916 scanned packages
  6 vulnerabilities require manual review. See the full report for details.

I don't know what is bad..............................................................


                       === npm audit security report ===

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nwb [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nwb > karma > log4js > loggly > request > hawk > boom > hoek │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nwb [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nwb > karma > log4js > loggly > request > hawk > cryptiles > │
│               │ boom > hoek                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nwb [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nwb > karma > log4js > loggly > request > hawk > hoek        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nwb [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nwb > karma > log4js > loggly > request > hawk > sntp > hoek │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Memory Exposure                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tunnel-agent                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.6.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nwb [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nwb > karma > log4js > loggly > request > tunnel-agent       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/598                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ timespan                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nwb [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nwb > karma > log4js > loggly > timespan                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/533                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 6 vulnerabilities (1 low, 5 moderate) in 17916 scanned packages
  6 vulnerabilities require manual review. See the full report for details.

**Comment by rrocher** [comment]
Any updates on this? I have the same issue, is there a fix for that? thanks
