### ISSUE TITLE
error on demo page - no pdf view

### ISSUE THREAD

**Issue by flckv** [agentcooper/react-pdf-highlighter#272]
"﻿react-pdf-highlighte…32839601376722394:1 Access to fetch at 'https://arxiv.org/pdf/1708.08021.pdf' from origin 'https://agentcooper.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

![image](https://github.com/agentcooper/react-pdf-highlighter/assets/103381497/a0625ed9-4870-479c-8e07-e1f6ac48bed5)

**Comment by LikeDreamwalker** [comment]
Same issues here and please change the source link

**Comment by AlfredMadere** [comment]
Still an issue! I can create a pr for this if the maintainer is willing to merge it

**Comment by agentcooper** [comment]
@AlfredMadere Yes please! I guess Arxiv no longer provides CORS.

**Comment by agentcooper** [comment]
Fixed in #274.
