### ISSUE TITLE
Debounced method called with different contexts

### ISSUE THREAD

**Issue by dkazakov8** [agentcooper/react-pdf-highlighter#276]
Hello,

I just upgraded to version 7.0.0, and when I resize the window, this error appears in the console: "Uncaught Error: Debounced method called with different contexts." This occurs inside the "debounce" library, and the root cause is [this line](https://github.com/agentcooper/react-pdf-highlighter/blob/main/src/components/PdfHighlighter.tsx#L557). The `debouncedScaleValue` method has no bound context, so when it's used in ResizeObserver or addEventListener, it has different contexts.

It seems like this error doesn't negatively affect functionality; it just spams the console with errors. `this.debouncedScaleValue = this.debouncedScaleValue.bind(this)` helps, maybe someone could include it in a PR.

![ksnip_20240712-212106](https://github.com/user-attachments/assets/876c44be-e46c-46e9-bece-be75ae46016f)

**Comment by agentcooper** [comment]
Thanks, I'll take a look. Does the 7.0.0 work fine for you otherwise?

**Comment by youlandEric** [comment]
> Thanks, I'll take a look. Does the 7.0.0 work fine for you otherwise?

Please update it. Thank you

**Comment by dkazakov8** [comment]
> Thanks, I'll take a look. Does the 7.0.0 work fine for you otherwise?

Yes, thanks. Everything else is working fine. The only difference from version 6.1.0 in my use cases was an incorrect z-index for the annotations layer (annotations are not clickable), which I fixed with:

```
.PdfHighlighter__highlight-layer {
  z-index: 3 !important;
}
```

**Comment by israel-arvizu** [comment]
Also encountering this issue on 7.0.0, any update?

**Comment by codepeach** [comment]
Same here, having the same issue

**Comment by NathanHam16** [comment]
Simple bandaid solution is to replace:

```debouncedScaleValue: () => void = debounce(this.handleScaleValue, 500);``` with
```  debouncedScaleValue = this.handleScaleValue;```

Keep in mind that removing debouncing may result in severe performance losses for resizing functionality.

**Comment by WangTing121314** [comment]
Same here, having the same issue

**Comment by agentcooper** [comment]
I switched to a different debounce library in `8.0.0-rc.0`.
