### ISSUE TITLE
Recent update in pdfjs causes incorrect worker to get loaded due to "^" dependency

### ISSUE THREAD

**Issue by floada-erik** [agentcooper/react-pdf-highlighter#279]
Hi, 

I just upgraded to version 7.0.0 but found an issue which I assume exists in the main code base as well when it is re-built again.
I get an error, saying that the worker and pdfViewer does not match. Problem is that react-pdf-highlighter since a couple of days back get the [4.5.136](https://www.npmjs.com/package/pdfjs-dist/v/4.5.136) version of pdfjs-dist and then the "worker" set in the [PdfLoader](https://github.com/agentcooper/react-pdf-highlighter/blob/14e4e7ccc2a9cd40461f53ce7925482a08a368a4/src/components/PdfLoader.tsx#L31)'s defaultProps does not match.  

I use pnpm so i can fix it myself using in my own package.json file:
```
  "pnpm": {
    "overrides": {
      "pdfjs-dist": "4.4.168"
    }
  },
```
 ...but a change in [package.json](https://github.com/agentcooper/react-pdf-highlighter/blob/14e4e7ccc2a9cd40461f53ce7925482a08a368a4/package.json#L31) where we lock down the pdfjs-dist version would be preferred I believe to make sure the worker version matches the pdfviewer version.

**Comment by fcFn** [comment]
Note that when that happens, the component will silently fail. To see the error, pass a component that accepts an `error` prop to `errorMessage` prop on the `PdfLighter`.

**Comment by agentcooper** [comment]
Thanks for the bug report! I pinned `pdfjs-dist` version in `8.0.0-rc.0`.
