### ISSUE TITLE
adaptive problem

### ISSUE THREAD

**Issue by kenphil** [agentcooper/react-pdf-highlighter#33]
How to make the width of the pdf document zoom in with the size of the container
```
<div style={{width: flag ? winWidth * 0.88 : winWidth * 0.63, position: "relative"}}>
    <PdfLoader url={this.state.url}>
        {
            pdfDocument=> (<PdfAnnotator {...props}/>)
        }
    </PdfLoader>
</div>
```

**Comment by jsg2021** [comment]
I got a ref to the PdfHighlighter component (PdfAnnotator in your comment) and on resize events, simply re-assign: `ref.viewer.currentScaleValue = 'page-width';`
