### ISSUE TITLE
highlight co-ordinates are changing from screen to screen

### ISSUE THREAD

**Issue by SelvaSurukam** [agentcooper/react-pdf-highlighter#35]
Hi @agentcooper,

Highlight co-ordinates are changing from screen(15.6) to screen(17.3). But when I add highlight with 17.3 and try to navigate that highlight from 15.6. It is automatically highlighting the exact place.

How you are achieving this functionalities without maintaining metadata information of client screen.

I am trying to achieve pdf text extraction with bounding box and with that some important tet bounding box I am trying to navigate in reac-pdf-highlighter.

I want to match this two bounding box.

Please do help me in this ASAP.

**Comment by agentcooper** [comment]
Highlights do contain the information about the original screen size: https://github.com/agentcooper/react-pdf-highlighter/blob/master/src/lib/coordinates.js#L24.

**Comment by SelvaSurukam** [comment]
Hi @agentcooper,

Thanks for quick reply, Is there a way to set the original pdf width and height while rendering.

**Comment by agentcooper** [comment]
Why do you need this? The web is responsive and the PDF will adapt to the size of the DOM container.

**Comment by SelvaSurukam** [comment]
@agentcooper closing this issue, because we don't need to actual pdf width and height while rendering.

Instead of that after selection, I am able to can convert to original bounding box.
