### ISSUE TITLE
Get PDF Coordinates from Selection

### ISSUE THREAD

**Issue by marija17** [agentcooper/react-pdf-highlighter#37]
I'm looking for a way to get PDF coordinates/points from a highlighted rectangular selection.  So far I've been able to understand that the PDFHighlighter component is using both scaled and viewport coordinates for my selections, however I'm not able to figure out where or if I can extract actual PDF coordinates from them.  Can anyone point me in the right direction for this?

**Comment by Nicba1010** [comment]
Hi, sorry, but can you answer this? Is this possible?
