### ISSUE TITLE
Adding page borders /margins

### ISSUE THREAD

**Issue by javaguy** [agentcooper/react-pdf-highlighter#4]
Hey @agentcooper thanks for putting together this sample, it's been very helpful. I'm trying to add back page borders and other margin/padding, but having trouble adjusting the highlight layer to accomodate.  How would someone compensate for these margins in the highlight layer?

**Comment by agentcooper** [comment]
Maybe adjust it in https://github.com/agentcooper/react-pdf-annotator/blob/master/src/style/pdf_viewer.css#L8?
