### ISSUE TITLE
Using custom path for worker.js

### ISSUE THREAD

**Issue by vsvanshi** [agentcooper/react-pdf-highlighter#43]
Hi, 
Can you please tell how to provide a custom worker.js path to react-pdf-highlighter.
pdfjs gives it in their options 
`pdfjsLib.GlobalWorkerOptions.workerSrc = '<any relative or absolute path>';`
So that we have workaround for issues like compatibility with webpack 4 and worker files not able to load on environments like nextjs.

**Comment by agentcooper** [comment]
I've updated the pdfjs-dist and recreated example using Create React App, it now should work out of the box. Let me know if you're still having troubles.
