### ISSUE TITLE
Delete a highlight

### ISSUE THREAD

**Issue by jfernal** [agentcooper/react-pdf-highlighter#45]
Hello, I would like remove a highlight when I click on "X" letter, placed before  highlight.comment.text. Do you have any solution?

Could you help me?.

**Comment by jinman** [comment]
Since there is no way to edit a Highlight, is it possible to get some API or documentation on how we can delete the highlight (so we can recreate it)? This is a fantastic library, please kind provide some direction or documentation for doing the same. Thank you.

**Comment by fpaupier** [comment]
Hi @jinman, did you find a way to remove an existing highlight?

**Comment by fpaupier** [comment]
@jinman, @jfernal 

You can remove an highlight programmatically by adding this function to your App class inside `src/App.js`

```js
  // removes the highlight of given id from internal array of highlights
  removeHighlight(id) {
    console.log("App::removeHighlight(): highlight Id=", id);
    this.setState(prevState => {
      return {
        ...prevState,
        highlights: prevState.highlights.filter(h => h.id !== id)
      }
    })
  }
```

Removing an highlight from the `highlights` state variable will remove the visual highlighting over the pdf.
