### ISSUE TITLE
Highlight adjacent page content

### ISSUE THREAD

**Issue by raseemayatt** [agentcooper/react-pdf-highlighter#46]
@agentcooper  While trying to select content spanning multiple pages, the content from second page is not highlighted. see the attached link

![Screenshot from 2019-07-25 12-22-47](https://user-images.githubusercontent.com/13759512/61853143-c9018600-aed8-11e9-9bbc-e97db1e4132d.png)

![Highlighted Screenshot  2019-07-25 12-25-12](https://user-images.githubusercontent.com/13759512/61853142-c868ef80-aed8-11e9-996a-dc4c26b87e54.png)

**Comment by agentcooper** [comment]
Closed in #164.
