### ISSUE TITLE
is there a way to use react-pdf-highlighter as a npm package when i don't use flow?

### ISSUE THREAD

**Issue by gzm1997** [agentcooper/react-pdf-highlighter#48]
hi, i want to use react-pdf-highlighter as a npm package in my project, but i can't use flow in my project. what can i do to deal with the "import type" in demo App.js?
![image](https://user-images.githubusercontent.com/15107912/67945245-69262400-fc19-11e9-9066-1cb7030ff69c.png)

and i found the types.js in eact-pdf-highlighter npm package is empty, how can i import and use T_Highlight type?
![image](https://user-images.githubusercontent.com/15107912/67946811-164e6b80-fc1d-11e9-96ef-328a605fc13c.png)

**Comment by agentcooper** [comment]
Take a look at the `lib` directory, it contains the compiled code without Flow. It will be used when you import the package as package.json specifies `"main": "lib/index.js",`

**Comment by gzm1997** [comment]
> Take a look at the `lib` directory, it contains the compiled code without Flow. It will be used when you import the package as package.json specifies `"main": "lib/index.js",`

is there any example that work without flow?
