### ISSUE TITLE
is it possible to place the highlighted text in the middle of the page?

### ISSUE THREAD

**Issue by raghu044** [agentcooper/react-pdf-highlighter#52]
Or is there any way to scroll back a little bit so the highlighted text will be visible at the middle?

**Comment by agentcooper** [comment]
Not at the moment.

**Comment by davidkong0987** [comment]
If you are okay with editing the module yourself, setting `scrollMargin` in (PdfHighlighter.js) to `window.PdfViewer.viewer.container.offsetHeight/2` works for me
