### ISSUE TITLE
Convert screenshot when load

### ISSUE THREAD

**Issue by atraining** [agentcooper/react-pdf-highlighter#54]
IIn Sidebar.js I have seen

```html
<img src={highlight.content.image} alt={"Screenshot"} />
```

In my case I only have the coordinates of the boundingRect I want to display. What is the easiest way to create the image (content.image) from the HTMLCanvas when the page loads the first time?

In the demo/sr/App.js the image is first rendered when the boundingRect changes

```javascript
                 <AreaHighlight
                      highlight={highlight}
                      onChange={boundingRect => {
                        this.updateHighlight(
                          highlight.id,
                          { boundingRect: viewportToScaled(boundingRect) },
                          { image: screenshot(boundingRect) }
                        );
                      }}
                    />
```

**Comment by agentcooper** [comment]
Would exposing `ref` on `<PdfHighlighter />` help?

```javascript
<PdfHighlighter
  ref={pdfHighlighter => {
    // save instance
    this.pdfHighlighter = pdfHighlighter;
  }}
  {...restProps}
/>;

// later
this.pdfHighlighter.screenshot(/* ... */);
```

**Comment by qbdchandresh009** [comment]
> Would exposing `ref` on `<PdfHighlighter />` help?
> 
> ```js
> <PdfHighlighter
>   ref={pdfHighlighter => {
>     // save instance
>     this.pdfHighlighter = pdfHighlighter;
>   }}
>   {...restProps}
> />;
> 
> // later
> this.pdfHighlighter.screenshot(/* ... */);
> ```

this is give me blank image
please help me
