### ISSUE TITLE
Is it possible to open PdfHighlighter in a viewer with the toolbar?

### ISSUE THREAD

**Issue by bojantv** [agentcooper/react-pdf-highlighter#55]

**Comment by agentcooper** [comment]
If you're talking about the toolbar as on https://mozilla.github.io/pdf.js/web/viewer.html, then the answer is no, however it might be simple enough to add since the code is already inside pdf.js.

**Comment by bojantv** [comment]
Thanks. I'll have a go at it. Nice project btw.

**Comment by jinman** [comment]
Are there any steps to add this toolbar? We would also like to add a toolbar on the top, can you please provide some direction on how to add this with react-pdf-highlighter?
