### ISSUE TITLE
Accessing the PDF content

### ISSUE THREAD

**Issue by Cremz** [agentcooper/react-pdf-highlighter#59]
Is there a way to send the PSD (with highlights) as base64 to a server, for example after a highlight is added or.
I don't care if the highlights are merged and won't be able to alter them after save, but so far this is the tool that would help me in my project and seems to work perfectly. Saving is the only thing i couldn't spot in your docs/code (I might be blind though)

**Comment by agentcooper** [comment]
I didn't explore base64, but I did [some prototyping to merge the highlights into the PDF](https://github.com/agentcooper/pdf-annotation-service) itself so you can view them with any viewer. Maybe from there you can go to base64.

**Comment by vidhyazworld** [comment]
@Cremz  My requirement is also the same, Have you figured out how to do it. If so please share.
