### ISSUE TITLE
is react-pdf-highlighter npm package broken ?

### ISSUE THREAD

**Issue by vamonte** [agentcooper/react-pdf-highlighter#65]
I not able to use your package in my own project.
My project use webpack and babel to build my files. (transform es6 files, minimize files ...)
When I import your package's classes, I have one error in webpack because your built files use es6 syntax.

Is it normal that your built files use the es6 syntax ?
How do you use / build your project that import this package ?

Thank's for your work.

**Comment by vamonte** [comment]
Ok I clone your project and I add @babel/preset-env to transform your files. It's work for me ;)

**Comment by toastedcrumpets** [comment]
Are you OK to close the issue then?
