### ISSUE TITLE
The search function rewrites over pdf

### ISSUE THREAD

**Issue by elisabetta-riskapp** [agentcooper/react-pdf-highlighter#69]
Hello Artem,
Whenever I try to search inside the document it looks weird. This is what happens inside the demo:
![search error](https://i.ibb.co/mJxkCcp/Screenshot-2020-05-20-at-17-05-39.png)
Any idea why? It kind of writes over the text. It only happens on chrome and edge - on safari and firefox it works just fine.

Thank you!

**Comment by ChrisSabau** [comment]
Bumping this up. I've seen this issue show up for me as well on chrome. Has anyone found a solution to this?

**Comment by mkachanov-exos** [comment]
Also looking for a solution
