### ISSUE TITLE
PDFLinkService is not a constructor

### ISSUE THREAD

**Issue by dvidalg** [agentcooper/react-pdf-highlighter#78]
Hi,

I'm just trying this component but got that error when loading the pfd:

Uncaught (in promise) TypeError: pdfjs_dist_web_pdf_viewer__WEBPACK_IMPORTED_MODULE_4__.PDFLinkService is not a constructor

The line in question is:
    this.linkService = new PDFLinkService();

In the pdf_viewer.js file of pdfjs-dist PDFLinkService is defined as a function not a class:
var PDFLinkService = function () {
...

What I'm doing wrong?
How can I solve this to try the test app?

Thanks and best regards :)

**Comment by dvidalg** [comment]
If I use the sample test app exactly as is in git "https://github.com/agentcooper/react-pdf-highlighter/tree/master/packages/example" it seems to work but shows an error "Critical dependency: require function is used in a way in which dependencies cannot be statically extracted"

But if I try to use it in my project (almost copying the app.js with only few modifications) it does not work and give to me the "PDFLinkService is not a constructor" error

I have seen a file "jest.config.js" in the sample that I do not know what is it.
I'm using webpack and babel, I don't know if I have to make some changes to my webpack.config.js or to package.json to get it working

Any help please?

Thanks and best regards.

**Comment by jsg2021** [comment]
What does your import statement look like? Are you trying to construct the link service or is this an error while using this library?

**Comment by dvidalg** [comment]
I will try to explain myself.

Scenario 1:
- I download the entire github code pressing the download code button on "https://github.com/agentcooper/react-pdf-highlighter"
- I copy only the content of the "https://github.com/agentcooper/react-pdf-highlighter/tree/master/packages/example" folder into a folder in my hard disk
- Open console and go to that folder in my hard disk
- npm install
- npm start
- All seems to work ok (except by an error on the console telling Critical dependency: require function is used in a way in which dependencies cannot be statically extracted")


Scenario 2:
- I copy this example folder in my hard disk into my proyect's folder (where I have all my react pages and components)
- Add this line to the index.js where I "declare" all my main accesible components
export App from "./pdf-example/App"
- npm install
- npm start
- Access my main page
- Open the new App component
- Got this error 
![image](https://user-images.githubusercontent.com/68819566/88513415-85a88e80-cfe8-11ea-9240-170fbf3d5222.png)

I use exactly the same code from your github in both scenarios, the only difference is that in my proyect I have not copied that other files and folders selected in blue
![image](https://user-images.githubusercontent.com/68819566/88513653-f94a9b80-cfe8-11ea-8f0c-4ebd67435b7e.png)

Any idea of where is the problem?

Thank you very much and best regards :)

**Comment by dvidalg** [comment]
One more comment, to be able to compile in scenario 2 I have removed // @flow and all types because if not I get errors due to that my proyect is in ReactJSX
Could be that the problem?

**Comment by jsg2021** [comment]
> One more comment, to be able to compile in scenario 2 I have removed // @flow and all types because if not I get errors due to that my proyect is in ReactJSX
> 
> Could be that the problem?

I doubt that would be the problem. If you control the babel config, there is a flow type plugin that strips the types. 

The error in your scenario 2 is strange. That looks like pdfjs-dist exports changed. If you delete the package-lock and reinstall node_modules, does it fix? 

This project uses lerna, and I'm not sure it honors the lock file when bootstrapping the mono-repo's dependencies. So the lock-file may be out of date.

**Comment by dvidalg** [comment]
Thanks for your reply :)

Now I'm very busy with other more urgent code.
I will try it on some days and report you.


   Thank you very much and best regards :)

**Comment by dvidalg** [comment]
Hi again,

I have tried to delete the package-lock.json file and run "npm install" in my proyect's folder, but the error still the same.

Any help?


   Thank you very much and best regards :)

**Comment by dvidalg** [comment]
Ok, I deleted the the node_modules folder and run again npm install
Now it works after some fixes.
The problem was that I was using an old versin of "react-pdf-js" (different from "react-pdfjs") that probably uses an old version of any component that causes the problem.

Thanks for the tips :)
