### ISSUE TITLE
scaling

### ISSUE THREAD

**Issue by cdpwest** [agentcooper/react-pdf-highlighter#82]
Hi,
I have written some code to export annotations from PDFs, however I am struggling to understand the scaling applied to the coordinates for the rectange in react-pdf-highlighter copared to the values generated directly from a pdf (using PDFbox to get the coordinates). Is it possible to explain the scaling that is applied to the x, y, height and width coordinates.

**Comment by brilhana** [comment]
Same issue. I have been using pdf.js-extract (Node.js) and  PyMuPDF (Python 3) and the coordinates seem correct and the scaling is incredibly off once in react-pdf-highlighter.

**Comment by cdpwest** [comment]
I found that the origin is the opposite way round to Adobe I.E (0,0) is the top left hand corner in Adobe but the bottom left hand corner in this implementation. Which is easily fixed by substitution of the value from the height.

**Comment by brilhana** [comment]
If I have:
```
boundingRect: {
    x1: 40.500204,
    y1: 414.899736,
    x2: 64.95702,
    y2: 424.919736,
    width: 24.456815999999996,
    height: 10.02
  },
```

what should it become to work with this implementation?
