### ISSUE TITLE
Create React App unable to locate worker

### ISSUE THREAD

**Issue by JonBergman** [agentcooper/react-pdf-highlighter#86]
I still get `Uncaught Error: Cannot find module 'worker-loader!pdfjs-dist/lib/pdf.worker'` on create-react-app applications.

react-scripts: `3.4.3`

**Comment by jsg2021** [comment]
If you import using the `worker-loader!`, you have to have the worker-loader installed.

**Comment by manoj529** [comment]
Hey Jsg2021 and Contributor, Really thank you for the wonderful extension.  Could you please help me to resolve the same error. 
I'm using Create React App application base code and added this sample plugin code. In another environment it worked without any error however when using it along with create-react-app sample code it throws an error giving the below message:

Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.
util.js:366 Warning: Setting up fake worker.
display_utils.js:501 Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.
main.chunk.worker.js:1 Uncaught SyntaxError: Unexpected token '<'

i tried installing worker-loader but it couldnt helped me to resolve this issue.
Any help would be really appreciated.

**Comment by G7495x** [comment]
const PDFWorker=`//cdnjs.cloudflare.com/ajax/libs/pdf.js/v5.0.0/pdf.worker.js`
setPdfWorker(PDFWorker)

Working...!

**Comment by fpaupier** [comment]
> If you import using the `worker-loader!`, you have to have the worker-loader installed.

Running `yarn add worker-loader --save-dev` in my create react app fixed the issue for me 👍
