### ISSUE TITLE
Page 15 does not render with the new release

### ISSUE THREAD

**Issue by theakashanand** [agentcooper/react-pdf-highlighter#87]
Certain pages (page 15 in the online example) do not render after updating to PDFJS v2.6.347

**Comment by jsg2021** [comment]
browser? The [online example](https://agentcooper.github.io/react-pdf-highlighter/) renders correctly for me?

**Comment by theakashanand** [comment]
![Screenshot 2020-09-20 at 5 15 05 PM](https://user-images.githubusercontent.com/58950873/93710487-dcec5a80-fb64-11ea-91b5-029863ceaa8e.jpg)

**Comment by theakashanand** [comment]
Am using Chrome 85.0.4183.102. The pages render initially, but after making a few highlights and scrolling around the pages fail to render

**Comment by filipbasara0** [comment]
Yes, I am having the same issue on Brave Version 1.7.98, Chromium: 81.0.4044.113 (tried on Mozilla as well and received the same error). After scrolling a little bit faster, many pages stop rendering.

**Comment by jsg2021** [comment]
This appears to be a pdfjs issue not one for this library.

**Comment by theakashanand** [comment]
When I had initially discovered this error, I thought it arose because there were issues with the new version of PDFjs. However, after diving in deeper, the issue does not seem like it can be attributed to PDFjs. I have a feeling that certain rendering tasks may be getting cancelled due to the Worker thread. PDFjs is able to successfully render the same pages when the worker is not created (when the app runs with a fakeWorker on the Main thread itself). Is there any particular reason the worker is being initiated with Port? 
Do look into this as it seems to be an issue with how the worker is being configured, and not with the pdfjs library itself.

**Comment by jsg2021** [comment]
> Is there any particular reason the worker is being initiated with Port?

Port is the Worker instance. Giving pdf.js communication lines to the worker and vice-versa. The setPdfWorker function attempts to set the correct config property depending on what you pass (a source url, a function, an instance etc)

**Comment by jsg2021** [comment]
> Do look into this as it seems to be an issue with how the worker is being configured, and not with the pdfjs library itself.

I don't believe there is any configuration. The source is all that is being set.
