### ISSUE TITLE
Different coordinates while highlighting the same pdf

### ISSUE THREAD

**Issue by gautampramesh** [agentcooper/react-pdf-highlighter#89]
I am highlighting a pdf using this tool in browser. My other use case is to pass the required highlights from backend and render in browser. However for the same text highlighted coordinates in browser are different than the coordinates passed from backend. Python fitz module is used to send the highlight coordinates from backend. As I missing something here that needs to be considered while highlighting and rendering(eg: coordinate units or anything else)

**Comment by davidkong0987** [comment]
Have you looked into `usePdfCoordinates`?

**Comment by ch-hristov** [comment]
An explanation on .usePdfCoordinates would be nice.

**Comment by davidkong0987** [comment]
This was a very long time ago  so I apologize not remembering exactly how it works. However, I do not recommend using it unless you are willing to go in and edit the source code as there is an error in `usePdfCoordinates`, which calls the `pdfToViewport(scaled, viewport)` function https://github.com/agentcooper/react-pdf-highlighter/issues/73

**Comment by agentcooper** [comment]
Fixed in #244.
