### ISSUE TITLE
Unable to fetch Japanese text from selected highlight

### ISSUE THREAD

**Issue by rishantagarwal** [agentcooper/react-pdf-highlighter#91]
While working with PDF's in Japanese , on creating a highlight, text is not selected correctly, although PDF renders without any problem.

<img width="307" alt="Screen Shot 2020-10-12 at 15 38 32" src="https://user-images.githubusercontent.com/2218422/95713274-3433a580-0ca1-11eb-81c5-cfd6a05de263.png">
<img width="574" alt="Screen Shot 2020-10-12 at 15 38 48" src="https://user-images.githubusercontent.com/2218422/95713279-35fd6900-0ca1-11eb-9e60-24e7341ae976.png">

@agentcooper

**Comment by agentcooper** [comment]
Try loading your PDF with the PDF.js viewer and see if the text is available there https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by rishantagarwal** [comment]
Just for anyone else who comes to this issue, this was an issue with how data was encoded into PDF and not with the library, so please check opening your PDF normally ( locally on your laptop) and see if you can copy paste text out of it or not, if not, then that PDF has issues
