### ISSUE TITLE
How to calculate boundingRect and rects in position

### ISSUE THREAD

**Issue by alex6liu** [agentcooper/react-pdf-highlighter#96]
![image](https://user-images.githubusercontent.com/41029702/99204934-156d8500-27f2-11eb-83cb-5e99624dfd45.png)
In the example, I saw you put the variables in test-highlights.js file.
For some reason, I want to highlight some sentences in the pdf like the test-highlights.js file. So the question is how to get the x1,y1,x2,y2,width and height?

Thanks for your help!

**Comment by slashgk** [comment]
@alex6liu Were you able to get the solution?

**Comment by alex6liu** [comment]
您好 您的邮件已收到我会尽快处理！
