### ISSUE TITLE
Dockerfile for development?

### ISSUE THREAD

**Issue by vsoch** [agentcooper/react-pdf-highlighter#97]
Hi! I'm looking to try this out via Docker, and I'm hoping to ask for your help for how to properly install and run the server because I keep running into bugs. My current recipe looks like the following:

```
FROM node:12
# docker build -t react-pdf-highlighter .

RUN mkdir -p /code
WORKDIR /code

# Install the remainder of our code.
COPY . /code
RUN npm install && \
    npm install packages/example && \
    npm install packages/react-pdf-highlighter && \
    npm install --save-dev babel-cli && \
    npm install react-scripts react worker-loader && \
    npm audit fix

EXPOSE 3000

ENTRYPOINT ["npm", "start"]
```
The standard `npm install` seems to miss many dependencies - does this lerna tool have some kind of install I am missing? I was working through various errors, but realize I probably just installed it incorrectly.

![image](https://user-images.githubusercontent.com/814322/100398460-e7ffb300-300b-11eb-8599-085ea9a13b9e.png)

Thanks so much for your help! I'll open a PR with the recipe and documentation when I can get this sorted out.

**Comment by agentcooper** [comment]
Hi! You probably want to run `npm run bootstrap` as well.
